{% set version = "2.6.1" %}

package:
  name: magma
  version: {{ version }} 

source:
   url: http://icl.utk.edu/projectsfiles/magma/downloads/magma-{{ version }}.tar.gz
   sha1: 08b9571a19b812ea4c48c24d76dc59781216e1f0
   patches:
    # 00xx - patch is carried forward from https://github.com/pytorch/builder/
    - 0001-cmakelists.patch
    - 0002-thread_queue.patch
    - 0003-make.inc.openblas-add-toolchain-overrides.patch
    - 0004-getrf_shfl.patch  # incorrect results for <7.0 arch
    - 0005-getrf_nbparam.patch  # fixes "too many resources requested for launch" error
    - 0006-CMake.patch # removes fermi for CUDA12+

build:
  number: 2
  string: cuda{{ cudatoolkit | replace(".*", "") }}_{{ PKG_BUILDNUM }} 
  script_env:
    - CUDA_HOME

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake {{ cmake }}
    - make
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}         # [x86_64 and c_compiler_version == "7.2.*"]
    - libstdcxx-ng  {{ libstdcxx }}   # [x86_64 and c_compiler_version == "7.2.*"]
  host:
    - openblas {{ openblas }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}         # [x86_64 and c_compiler_version == "7.2.*"]
    - libstdcxx-ng  {{ libstdcxx }}   # [x86_64 and c_compiler_version == "7.2.*"]
  run:
    - openblas {{ openblas }}
    - cudatoolkit {{ cudatoolkit }}

about:
  home: http://icl.cs.utk.edu/magma/software/index.html
  license: BSD
  license_family: BSD
  license_file: COPYRIGHT
  summary: Dense linear algebra library similar to LAPACK but for heterogeneous/hybrid architectures
  description: |
    Dense linear algebra library similar to LAPACK but for heterogeneous/hybrid architectures

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
