{% set version = "2.5.4" %}

package:
  name: magma
  version: {{ version }} 

source:
   url: http://icl.utk.edu/projectsfiles/magma/downloads/magma-{{ version }}.tar.gz
   sha1: c428c9486c5f46f3595570ec898274a8bb888d5c
   patches:
     - cmakelists.patch
     - thread_queue.patch
     - make.inc.openblas-add-toolchain-overrides.patch

build:
  number: 3
  string: cuda{{ cudatoolkit | replace(".*", "") }}_{{ PKG_BUILDNUM }} 
  script_env:
    - CUDA_HOME

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake {{ cmake }}
    - make
  host:
    - openblas {{ openblas }}
  run:
    - openblas {{ openblas }}
    - cudatoolkit {{ cudatoolkit }}

about:
  home: http://icl.cs.utk.edu/magma/software/index.html
  license: BSD
  license_family: BSD
  license_file: COPYRIGHT
  summary: Dense linear algebra library similar to LAPACK but for heterogeneous/hybrid architectures
  description: |
    Dense linear algebra library similar to LAPACK but for heterogeneous/hybrid architectures

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
